<?php
use Migrations\AbstractSeed;

/**
 * AppCharacters seed.
 */
class AppCharactersSeed extends AbstractSeed
{
    /**
     * Run Method.
     *
     * Write your database seeder using this method.
     *
     * More information on writing seeds is available here:
     * https://book.cakephp.org/phinx/0/en/seeding.html
     *
     * @return void
     */
    public function run()
    {
        $data = [
            [
                'id' => '1',
                'ext_id' => '58de7fd2179710000455a671',
                'status' => 'active',
                'slug' => 'dennis-roady',
                'title' => 'Dennis Roady',
                'is_influencer' => '1',
                'facebook_url' => 'https://www.facebook.com/dennisroady',
                'youtube_url' => 'https://www.youtube.com/user/howtoprankitup',
                'img_url' => 'http://cdn.prankerapp.com/prank-image/ZF8CAdxtnIIwdIc5.png',
                'ord' => '1000',
                'data' => '{"_id":"58de7fd2179710000455a671","slug":"dennis-roady","title":"Dennis Roady","isInfluencer":true,"__v":0,"facebookPageLink":"https:\\/\\/www.facebook.com\\/dennisroady","youtubeId":"howtoprankitup","image":{"mimetype":"image\\/png","size":70851,"filename":"ZF8CAdxtnIIwdIc5.png","url":"http:\\/\\/cdn.prankerapp.com\\/prank-image\\/ZF8CAdxtnIIwdIc5.png"}}',
                'created' => '2019-02-09 03:11:01',
                'modified' => '2020-07-01 06:53:29',
                'synced' => '2020-07-01 06:51:38',
            ],
            [
                'id' => '2',
                'ext_id' => '59137ab9e04806002ec81a84',
                'status' => 'active',
                'slug' => 'customer-service',
                'title' => 'Customer Service',
                'is_influencer' => '0',
                'facebook_url' => '',
                'youtube_url' => '',
                'img_url' => 'http://cdn.prankerapp.com/prank-assets/DefaultPrankImage.jpg',
                'ord' => '1000',
                'data' => '{"_id":"59137ab9e04806002ec81a84","slug":"customer-service","title":"Customer Service","isInfluencer":false,"__v":0,"image":{"url":"http:\\/\\/cdn.prankerapp.com\\/prank-assets\\/DefaultPrankImage.jpg"}}',
                'created' => '2019-02-09 03:11:01',
                'modified' => '2020-07-01 06:51:37',
                'synced' => '2020-07-01 06:51:37',
            ],
            [
                'id' => '3',
                'ext_id' => '587e1a29ddef7d0004e08b6d',
                'status' => 'active',
                'slug' => 'buk-lau',
                'title' => 'Buk Lau ',
                'is_influencer' => '1',
                'facebook_url' => 'https://www.facebook.com/OwnagePranks/',
                'youtube_url' => 'https://www.youtube.com/user/ownagepranks',
                'img_url' => 'http://cdn.prankerapp.com/prank-image/gVgkArMbKZRkMljj.png',
                'ord' => '4',
                'data' => '{"_id":"587e1a29ddef7d0004e08b6d","slug":"buk-lau","title":"Buk Lau ","__v":0,"image":{"mimetype":"image\\/png","size":11743,"filename":"gVgkArMbKZRkMljj.png","url":"http:\\/\\/cdn.prankerapp.com\\/prank-image\\/gVgkArMbKZRkMljj.png"},"facebookPageLink":"https:\\/\\/www.facebook.com\\/OwnagePranks\\/","isInfluencer":true,"youtubeId":"ownagepranks"}',
                'created' => '2019-02-09 03:11:02',
                'modified' => '2020-07-01 06:53:20',
                'synced' => '2020-07-01 06:51:38',
            ],
            [
                'id' => '4',
                'ext_id' => '58f22ece8990950022ccdfbe',
                'status' => 'active',
                'slug' => 'british',
                'title' => 'British',
                'is_influencer' => '0',
                'facebook_url' => '',
                'youtube_url' => '',
                'img_url' => 'http://cdn.prankerapp.com/prank-image/gXuOfl3H6KFhr-nb.png',
                'ord' => '1000',
                'data' => '{"_id":"58f22ece8990950022ccdfbe","slug":"british","title":"British","isInfluencer":false,"__v":0,"image":{"mimetype":"image\\/png","size":24328,"filename":"gXuOfl3H6KFhr-nb.png","url":"http:\\/\\/cdn.prankerapp.com\\/prank-image\\/gXuOfl3H6KFhr-nb.png"}}',
                'created' => '2019-02-09 03:11:02',
                'modified' => '2020-07-01 06:53:49',
                'synced' => '2020-07-01 06:51:39',
            ],
            [
                'id' => '5',
                'ext_id' => '58f6565765e8ed00229c2649',
                'status' => 'active',
                'slug' => 'angry-girlfriend',
                'title' => 'Angry Girlfriend ',
                'is_influencer' => '0',
                'facebook_url' => '',
                'youtube_url' => '',
                'img_url' => 'http://cdn.prankerapp.com/prank-image/--GdcdhR3FA-KuPq.png',
                'ord' => '1000',
                'data' => '{"_id":"58f6565765e8ed00229c2649","slug":"angry-girlfriend","title":"Angry Girlfriend ","isInfluencer":false,"__v":0,"image":{"mimetype":"image\\/png","size":15215,"filename":"--GdcdhR3FA-KuPq.png","url":"http:\\/\\/cdn.prankerapp.com\\/prank-image\\/--GdcdhR3FA-KuPq.png"}}',
                'created' => '2019-02-09 03:11:02',
                'modified' => '2020-07-01 06:52:52',
                'synced' => '2020-07-01 06:51:39',
            ],
            [
                'id' => '6',
                'ext_id' => '58f64425a049dd002ea3756b',
                'status' => 'active',
                'slug' => 'pharmacist',
                'title' => 'Pharmacist ',
                'is_influencer' => '0',
                'facebook_url' => '',
                'youtube_url' => '',
                'img_url' => 'http://cdn.prankerapp.com/prank-image/qXwLl89NcRhn3lyn.png',
                'ord' => '1000',
                'data' => '{"_id":"58f64425a049dd002ea3756b","slug":"pharmacist","title":"Pharmacist ","isInfluencer":false,"__v":0,"image":{"mimetype":"image\\/png","size":14197,"filename":"qXwLl89NcRhn3lyn.png","url":"http:\\/\\/cdn.prankerapp.com\\/prank-image\\/qXwLl89NcRhn3lyn.png"}}',
                'created' => '2019-02-09 03:11:02',
                'modified' => '2020-07-01 06:53:23',
                'synced' => '2020-07-01 06:51:40',
            ],
            [
                'id' => '7',
                'ext_id' => '588cd4004e845d0004e4acbf',
                'status' => 'active',
                'slug' => 'evil-kid',
                'title' => 'Evil Kid',
                'is_influencer' => '0',
                'facebook_url' => '',
                'youtube_url' => '',
                'img_url' => 'http://cdn.prankerapp.com/prank-image/cYeWKoi0IWAJBqkq.png',
                'ord' => '1000',
                'data' => '{"_id":"588cd4004e845d0004e4acbf","slug":"evil-kid","title":"Evil Kid","__v":0,"image":{"mimetype":"image\\/png","size":21579,"filename":"cYeWKoi0IWAJBqkq.png","url":"http:\\/\\/cdn.prankerapp.com\\/prank-image\\/cYeWKoi0IWAJBqkq.png"}}',
                'created' => '2019-02-09 03:11:02',
                'modified' => '2020-07-01 06:53:28',
                'synced' => '2020-07-01 06:51:39',
            ],
            [
                'id' => '8',
                'ext_id' => '58b85f9ecf7e940004a8c8c3',
                'status' => 'active',
                'slug' => 'flula',
                'title' => 'Flula',
                'is_influencer' => '1',
                'facebook_url' => 'https://www.facebook.com/flula/',
                'youtube_url' => 'https://www.youtube.com/user/djflula',
                'img_url' => 'http://cdn.prankerapp.com/prank-image/9pBhejVMfBQthRzV.png',
                'ord' => '1000',
                'data' => '{"_id":"58b85f9ecf7e940004a8c8c3","slug":"flula","title":"Flula","__v":0,"image":{"mimetype":"image\\/png","size":40225,"filename":"9pBhejVMfBQthRzV.png","url":"http:\\/\\/cdn.prankerapp.com\\/prank-image\\/9pBhejVMfBQthRzV.png"},"facebookPageLink":"https:\\/\\/www.facebook.com\\/flula\\/","isInfluencer":true,"youtubeId":"djflula"}',
                'created' => '2019-02-09 03:11:03',
                'modified' => '2020-07-01 06:53:25',
                'synced' => '2020-07-01 06:51:40',
            ],
            [
                'id' => '9',
                'ext_id' => '58c2ac805b74ba000483f2f6',
                'status' => 'active',
                'slug' => 'automated-message',
                'title' => 'Automated Message',
                'is_influencer' => '0',
                'facebook_url' => '',
                'youtube_url' => '',
                'img_url' => 'http://cdn.prankerapp.com/prank-image/z8-hbq467EkzWmYA.png',
                'ord' => '1000',
                'data' => '{"_id":"58c2ac805b74ba000483f2f6","slug":"automated-message","title":"Automated Message","__v":0,"image":{"mimetype":"image\\/png","size":50503,"filename":"z8-hbq467EkzWmYA.png","url":"http:\\/\\/cdn.prankerapp.com\\/prank-image\\/z8-hbq467EkzWmYA.png"}}',
                'created' => '2019-02-09 03:11:03',
                'modified' => '2020-07-01 06:53:28',
                'synced' => '2020-07-01 06:51:40',
            ],
            [
                'id' => '10',
                'ext_id' => '587e1a43ddef7d0004e08b6e',
                'status' => 'active',
                'slug' => 'tyrone',
                'title' => 'Tyrone',
                'is_influencer' => '1',
                'facebook_url' => 'https://www.facebook.com/OwnagePranks/',
                'youtube_url' => 'https://www.youtube.com/user/OwnagePranks',
                'img_url' => 'http://cdn.prankerapp.com/prank-image/iKXi0dUT1-QbjBN4.png',
                'ord' => '8',
                'data' => '{"_id":"587e1a43ddef7d0004e08b6e","slug":"tyrone","title":"Tyrone","__v":0,"image":{"mimetype":"image\\/png","size":13173,"filename":"iKXi0dUT1-QbjBN4.png","url":"http:\\/\\/cdn.prankerapp.com\\/prank-image\\/iKXi0dUT1-QbjBN4.png"},"facebookPageLink":"https:\\/\\/www.facebook.com\\/OwnagePranks\\/","isInfluencer":true,"youtubeId":"OwnagePranks"}',
                'created' => '2019-02-09 03:11:03',
                'modified' => '2020-07-01 06:53:25',
                'synced' => '2020-07-01 06:51:41',
            ],
            [
                'id' => '11',
                'ext_id' => '594958edd988df0017d5ffbf',
                'status' => 'active',
                'slug' => 'hellthyjunkfood',
                'title' => 'HellthyJunkFood',
                'is_influencer' => '1',
                'facebook_url' => 'https://www.facebook.com/Hellthyjunkfood/',
                'youtube_url' => 'https://www.youtube.com/user/HellthyJunkFood',
                'img_url' => 'http://cdn.prankerapp.com/prank-image/7inNL2W9i7zEqwoL.png',
                'ord' => '1000',
                'data' => '{"_id":"594958edd988df0017d5ffbf","slug":"hellthyjunkfood","title":"HellthyJunkFood","isInfluencer":true,"__v":0,"facebookPageLink":"https:\\/\\/www.facebook.com\\/Hellthyjunkfood\\/","youtubeId":"HellthyJunkFood","description":"JP","image":{"mimetype":"image\\/png","size":19388,"filename":"7inNL2W9i7zEqwoL.png","url":"http:\\/\\/cdn.prankerapp.com\\/prank-image\\/7inNL2W9i7zEqwoL.png"}}',
                'created' => '2019-02-09 03:11:03',
                'modified' => '2020-07-01 06:53:18',
                'synced' => '2020-07-01 06:51:42',
            ],
            [
                'id' => '12',
                'ext_id' => '587e1a5cddef7d0004e08b70',
                'status' => 'active',
                'slug' => 'juan',
                'title' => 'Juan',
                'is_influencer' => '1',
                'facebook_url' => 'https://www.facebook.com/OwnagePranks/',
                'youtube_url' => 'https://www.youtube.com/user/OwnagePranks',
                'img_url' => 'http://cdn.prankerapp.com/prank-image/P5J4bUNdJbjRkaE7.png',
                'ord' => '1',
                'data' => '{"_id":"587e1a5cddef7d0004e08b70","slug":"juan","title":"Juan","__v":0,"image":{"mimetype":"image\\/png","size":19547,"filename":"P5J4bUNdJbjRkaE7.png","url":"http:\\/\\/cdn.prankerapp.com\\/prank-image\\/P5J4bUNdJbjRkaE7.png"},"facebookPageLink":"https:\\/\\/www.facebook.com\\/OwnagePranks\\/","isInfluencer":true,"youtubeId":"OwnagePranks"}',
                'created' => '2019-02-09 03:11:03',
                'modified' => '2020-07-01 06:53:15',
                'synced' => '2020-07-01 06:51:41',
            ],
            [
                'id' => '13',
                'ext_id' => '58f4f5b0acb444001b109190',
                'status' => 'active',
                'slug' => 'aussie',
                'title' => 'Aussie',
                'is_influencer' => '0',
                'facebook_url' => '',
                'youtube_url' => '',
                'img_url' => 'http://cdn.prankerapp.com/prank-image/IpAlWHjUrK2z7XSy.png',
                'ord' => '1000',
                'data' => '{"_id":"58f4f5b0acb444001b109190","slug":"aussie","title":"Aussie","isInfluencer":false,"__v":0,"image":{"mimetype":"image\\/png","size":15215,"filename":"IpAlWHjUrK2z7XSy.png","url":"http:\\/\\/cdn.prankerapp.com\\/prank-image\\/IpAlWHjUrK2z7XSy.png"}}',
                'created' => '2019-02-09 03:11:03',
                'modified' => '2020-07-01 06:53:48',
                'synced' => '2020-07-01 06:51:41',
            ],
            [
                'id' => '14',
                'ext_id' => '5887863cc7a556000448bdef',
                'status' => 'active',
                'slug' => 'billy',
                'title' => 'Billy',
                'is_influencer' => '1',
                'facebook_url' => 'https://www.facebook.com/OwnagePranks/',
                'youtube_url' => 'https://www.youtube.com/user/ownagepranks',
                'img_url' => 'http://cdn.prankerapp.com/prank-image/oUJ2SBgMQSrcTnnW.png',
                'ord' => '6',
                'data' => '{"_id":"5887863cc7a556000448bdef","slug":"billy","title":"Billy","__v":0,"image":{"mimetype":"image\\/png","size":15927,"filename":"oUJ2SBgMQSrcTnnW.png","url":"http:\\/\\/cdn.prankerapp.com\\/prank-image\\/oUJ2SBgMQSrcTnnW.png"},"facebookPageLink":"https:\\/\\/www.facebook.com\\/OwnagePranks\\/","isInfluencer":true,"youtubeId":"ownagepranks"}',
                'created' => '2019-02-09 03:11:03',
                'modified' => '2020-07-01 06:53:36',
                'synced' => '2020-07-01 06:51:42',
            ],
            [
                'id' => '15',
                'ext_id' => '58f22f4318c54f002e7be418',
                'status' => 'active',
                'slug' => 'librarian',
                'title' => 'Librarian ',
                'is_influencer' => '0',
                'facebook_url' => '',
                'youtube_url' => '',
                'img_url' => 'http://cdn.prankerapp.com/prank-image/WQ3gnnrQbM5PZOrt.png',
                'ord' => '1000',
                'data' => '{"_id":"58f22f4318c54f002e7be418","slug":"librarian","title":"Librarian ","isInfluencer":false,"__v":0,"image":{"mimetype":"image\\/png","size":15215,"filename":"WQ3gnnrQbM5PZOrt.png","url":"http:\\/\\/cdn.prankerapp.com\\/prank-image\\/WQ3gnnrQbM5PZOrt.png"}}',
                'created' => '2019-02-09 03:11:03',
                'modified' => '2020-07-01 06:53:28',
                'synced' => '2020-07-01 06:51:42',
            ],
            [
                'id' => '16',
                'ext_id' => '587e1a57ddef7d0004e08b6f',
                'status' => 'active',
                'slug' => 'rakesh',
                'title' => 'Rakesh',
                'is_influencer' => '1',
                'facebook_url' => 'https://www.facebook.com/OwnagePranks/',
                'youtube_url' => 'https://www.youtube.com/user/OwnagePranks',
                'img_url' => 'http://cdn.prankerapp.com/prank-image/GCZ4nGfKlBQCRPdQ.png',
                'ord' => '5',
                'data' => '{"_id":"587e1a57ddef7d0004e08b6f","slug":"rakesh","title":"Rakesh","__v":0,"image":{"mimetype":"image\\/png","size":13030,"filename":"GCZ4nGfKlBQCRPdQ.png","url":"http:\\/\\/cdn.prankerapp.com\\/prank-image\\/GCZ4nGfKlBQCRPdQ.png"},"facebookPageLink":"https:\\/\\/www.facebook.com\\/OwnagePranks\\/","isInfluencer":true,"youtubeId":"OwnagePranks"}',
                'created' => '2019-02-09 03:11:04',
                'modified' => '2020-07-01 06:53:29',
                'synced' => '2020-07-01 06:51:43',
            ],
            [
                'id' => '17',
                'ext_id' => '587df60addef7d0004e08b6a',
                'status' => 'active',
                'slug' => 'russell',
                'title' => 'Russell',
                'is_influencer' => '1',
                'facebook_url' => 'https://www.facebook.com/OwnagePranks/',
                'youtube_url' => 'https://www.youtube.com/user/OwnagePranks',
                'img_url' => 'http://cdn.prankerapp.com/prank-image/HjFAvHrDpfsNymu8.png',
                'ord' => '10',
                'data' => '{"_id":"587df60addef7d0004e08b6a","slug":"russell","title":"Russell","__v":0,"fileUrl":{"size":null,"mimetype":null,"url":null,"filename":null},"image":{"mimetype":"image\\/png","size":14288,"filename":"HjFAvHrDpfsNymu8.png","url":"http:\\/\\/cdn.prankerapp.com\\/prank-image\\/HjFAvHrDpfsNymu8.png"},"facebookPageLink":"https:\\/\\/www.facebook.com\\/OwnagePranks\\/","isInfluencer":true,"youtubeId":"OwnagePranks"}',
                'created' => '2019-02-09 03:11:04',
                'modified' => '2020-07-01 06:53:37',
                'synced' => '2020-07-01 06:51:42',
            ],
            [
                'id' => '18',
                'ext_id' => '5890b46eb460870004308316',
                'status' => 'active',
                'slug' => 'sexy-woman',
                'title' => 'Sexy Woman',
                'is_influencer' => '0',
                'facebook_url' => '',
                'youtube_url' => '',
                'img_url' => 'http://cdn.prankerapp.com/prank-image/m2M5ST0beqR98Zfj.png',
                'ord' => '1000',
                'data' => '{"_id":"5890b46eb460870004308316","slug":"sexy-woman","title":"Sexy Woman","__v":0,"image":{"mimetype":"image\\/png","size":25162,"filename":"m2M5ST0beqR98Zfj.png","url":"http:\\/\\/cdn.prankerapp.com\\/prank-image\\/m2M5ST0beqR98Zfj.png"}}',
                'created' => '2019-02-09 03:11:04',
                'modified' => '2020-07-01 06:52:53',
                'synced' => '2020-07-01 06:51:43',
            ],
            [
                'id' => '19',
                'ext_id' => '587e1a76ddef7d0004e08b71',
                'status' => 'active',
                'slug' => 'chris',
                'title' => 'Chris',
                'is_influencer' => '1',
                'facebook_url' => 'https://www.facebook.com/OwnagePranks/',
                'youtube_url' => 'https://www.youtube.com/user/OwnagePranks',
                'img_url' => 'http://cdn.prankerapp.com/prank-image/mMiUgxgtEQRP6n6I.png',
                'ord' => '3',
                'data' => '{"_id":"587e1a76ddef7d0004e08b71","slug":"chris","title":"Chris","__v":0,"image":{"mimetype":"image\\/png","size":13497,"filename":"mMiUgxgtEQRP6n6I.png","url":"http:\\/\\/cdn.prankerapp.com\\/prank-image\\/mMiUgxgtEQRP6n6I.png"},"facebookPageLink":"https:\\/\\/www.facebook.com\\/OwnagePranks\\/","isInfluencer":true,"youtubeId":"OwnagePranks"}',
                'created' => '2019-02-09 03:11:04',
                'modified' => '2020-07-01 06:51:43',
                'synced' => '2020-07-01 06:51:43',
            ],
            [
                'id' => '20',
                'ext_id' => '5891f7e594f35b0004bb7597',
                'status' => 'active',
                'slug' => 'alain-french-guy',
                'title' => 'Alain (French Guy)',
                'is_influencer' => '0',
                'facebook_url' => '',
                'youtube_url' => '',
                'img_url' => 'http://cdn.prankerapp.com/prank-image/O2GVZi-qT5QYh1IO.png',
                'ord' => '1000',
                'data' => '{"_id":"5891f7e594f35b0004bb7597","slug":"alain-french-guy","title":"Alain (French Guy)","__v":0,"image":{"mimetype":"image\\/png","size":15215,"filename":"O2GVZi-qT5QYh1IO.png","url":"http:\\/\\/cdn.prankerapp.com\\/prank-image\\/O2GVZi-qT5QYh1IO.png"}}',
                'created' => '2019-02-09 03:11:04',
                'modified' => '2020-07-01 06:53:15',
                'synced' => '2020-07-01 06:51:43',
            ],
            [
                'id' => '21',
                'ext_id' => '58c2b1f15b74ba000483f30f',
                'status' => 'active',
                'slug' => 'uber-driver',
                'title' => 'Uber Driver',
                'is_influencer' => '0',
                'facebook_url' => '',
                'youtube_url' => '',
                'img_url' => 'http://cdn.prankerapp.com/prank-assets/DefaultPrankImage.jpg',
                'ord' => '1000',
                'data' => '{"_id":"58c2b1f15b74ba000483f30f","slug":"uber-driver","title":"Uber Driver","__v":0,"image":{"url":"http:\\/\\/cdn.prankerapp.com\\/prank-assets\\/DefaultPrankImage.jpg"}}',
                'created' => '2019-02-09 03:11:04',
                'modified' => '2020-07-01 06:51:44',
                'synced' => '2020-07-01 06:51:44',
            ],
            [
                'id' => '22',
                'ext_id' => '5889fe7acbd6e50004e3b452',
                'status' => 'active',
                'slug' => 'old-man',
                'title' => 'Old Man',
                'is_influencer' => '0',
                'facebook_url' => '',
                'youtube_url' => '',
                'img_url' => 'http://cdn.prankerapp.com/prank-image/inIawTLjFHvSDQ9x.png',
                'ord' => '1000',
                'data' => '{"_id":"5889fe7acbd6e50004e3b452","slug":"old-man","title":"Old Man","__v":0,"image":{"mimetype":"image\\/png","size":15215,"filename":"inIawTLjFHvSDQ9x.png","url":"http:\\/\\/cdn.prankerapp.com\\/prank-image\\/inIawTLjFHvSDQ9x.png"}}',
                'created' => '2019-02-09 03:11:04',
                'modified' => '2020-07-01 06:53:24',
                'synced' => '2020-07-01 06:51:45',
            ],
            [
                'id' => '23',
                'ext_id' => '58f38644c5fa9c001c9ba680',
                'status' => 'active',
                'slug' => 'angry-mom',
                'title' => 'Angry Mom',
                'is_influencer' => '0',
                'facebook_url' => '',
                'youtube_url' => '',
                'img_url' => 'http://cdn.prankerapp.com/prank-image/eHkUOeAkX-44X0jN.png',
                'ord' => '1000',
                'data' => '{"_id":"58f38644c5fa9c001c9ba680","slug":"angry-mom","title":"Angry Mom","isInfluencer":false,"__v":0,"image":{"mimetype":"image\\/png","size":15215,"filename":"eHkUOeAkX-44X0jN.png","url":"http:\\/\\/cdn.prankerapp.com\\/prank-image\\/eHkUOeAkX-44X0jN.png"}}',
                'created' => '2019-02-09 03:11:05',
                'modified' => '2020-07-01 06:53:47',
                'synced' => '2020-07-01 06:51:44',
            ],
            [
                'id' => '24',
                'ext_id' => '588794b150e1040004324de3',
                'status' => 'active',
                'slug' => 'john',
                'title' => 'John',
                'is_influencer' => '1',
                'facebook_url' => 'https://www.facebook.com/OwnagePranks/',
                'youtube_url' => 'https://www.youtube.com/user/ownagepranks',
                'img_url' => 'http://cdn.prankerapp.com/prank-image/tJQH-XqKJ8CJLR93.png',
                'ord' => '2',
                'data' => '{"_id":"588794b150e1040004324de3","slug":"john","title":"John","__v":0,"image":{"mimetype":"image\\/png","size":15200,"filename":"tJQH-XqKJ8CJLR93.png","url":"http:\\/\\/cdn.prankerapp.com\\/prank-image\\/tJQH-XqKJ8CJLR93.png"},"facebookPageLink":"https:\\/\\/www.facebook.com\\/OwnagePranks\\/","isInfluencer":true,"youtubeId":"ownagepranks"}',
                'created' => '2019-02-09 03:11:05',
                'modified' => '2020-07-01 06:53:08',
                'synced' => '2020-07-01 06:51:45',
            ],
            [
                'id' => '25',
                'ext_id' => '594a56900c80930010e4c47d',
                'status' => 'active',
                'slug' => 'hellthyjunkfood-1',
                'title' => 'HellthyJunkFood',
                'is_influencer' => '1',
                'facebook_url' => 'https://www.facebook.com/Hellthyjunkfood/',
                'youtube_url' => 'https://www.youtube.com/user/HellthyJunkFood',
                'img_url' => 'http://cdn.prankerapp.com/prank-image/uGqmzgaKnKLxxXFp.png',
                'ord' => '1000',
                'data' => '{"_id":"594a56900c80930010e4c47d","slug":"hellthyjunkfood-1","title":"HellthyJunkFood","isInfluencer":true,"__v":0,"description":"Julia","image":{"mimetype":"image\\/png","size":22305,"filename":"uGqmzgaKnKLxxXFp.png","url":"http:\\/\\/cdn.prankerapp.com\\/prank-image\\/uGqmzgaKnKLxxXFp.png"},"facebookPageLink":"https:\\/\\/www.facebook.com\\/Hellthyjunkfood\\/","youtubeId":"HellthyJunkFood"}',
                'created' => '2019-02-09 03:11:05',
                'modified' => '2020-07-01 06:53:17',
                'synced' => '2020-07-01 06:51:44',
            ],
            [
                'id' => '26',
                'ext_id' => '590f5280ed55ab002265e61a',
                'status' => 'active',
                'slug' => 'cute-kid',
                'title' => 'Cute Kid',
                'is_influencer' => '0',
                'facebook_url' => '',
                'youtube_url' => '',
                'img_url' => 'http://cdn.prankerapp.com/prank-image/JEaiPhr36IKLqqml.png',
                'ord' => '1000',
                'data' => '{"_id":"590f5280ed55ab002265e61a","slug":"cute-kid","title":"Cute Kid","isInfluencer":false,"image":{"mimetype":"image\\/png","size":21139,"filename":"JEaiPhr36IKLqqml.png","url":"http:\\/\\/cdn.prankerapp.com\\/prank-image\\/JEaiPhr36IKLqqml.png"},"__v":0}',
                'created' => '2019-02-09 03:11:06',
                'modified' => '2020-07-01 06:53:28',
                'synced' => '2020-07-01 06:51:45',
            ],
            [
                'id' => '27',
                'ext_id' => '587df622ddef7d0004e08b6b',
                'status' => 'active',
                'slug' => 'abdo',
                'title' => 'Abdo',
                'is_influencer' => '1',
                'facebook_url' => 'https://www.facebook.com/OwnagePranks/',
                'youtube_url' => 'https://www.youtube.com/user/ownagepranks',
                'img_url' => 'http://cdn.prankerapp.com/prank-image/INjO2PxNimKvyZzi.png',
                'ord' => '7',
                'data' => '{"_id":"587df622ddef7d0004e08b6b","slug":"abdo","title":"Abdo","__v":0,"image":{"mimetype":"image\\/png","size":14645,"filename":"INjO2PxNimKvyZzi.png","url":"http:\\/\\/cdn.prankerapp.com\\/prank-image\\/INjO2PxNimKvyZzi.png"},"facebookPageLink":"https:\\/\\/www.facebook.com\\/OwnagePranks\\/","isInfluencer":true,"youtubeId":"ownagepranks"}',
                'created' => '2019-02-09 03:11:06',
                'modified' => '2020-07-01 06:53:20',
                'synced' => '2020-07-01 06:51:39',
            ],
            [
                'id' => '28',
                'ext_id' => '5994149dba7b0c0010243b09',
                'status' => 'inactive',
                'slug' => 'test',
                'title' => 'test',
                'is_influencer' => '0',
                'facebook_url' => '',
                'youtube_url' => '',
                'img_url' => 'http://cdn.prankerapp.com/prank-image/622WiceB1gUysbqr.jpg',
                'ord' => '1000',
                'data' => '{"_id":"5994149dba7b0c0010243b09","slug":"test","title":"test","isInfluencer":false,"image":{"mimetype":"image\\/jpeg","size":210392,"filename":"622WiceB1gUysbqr.jpg","url":"http:\\/\\/cdn.prankerapp.com\\/prank-image\\/622WiceB1gUysbqr.jpg"},"__v":0}',
                'created' => '2019-02-09 03:11:06',
                'modified' => '2020-07-01 06:53:58',
                'synced' => '2020-07-01 06:51:45',
            ],
            [
                'id' => '29',
                'ext_id' => '59baa2d550a4fa001731be08',
                'status' => 'inactive',
                'slug' => 'carmen',
                'title' => 'Carmen',
                'is_influencer' => '0',
                'facebook_url' => '',
                'youtube_url' => '',
                'img_url' => 'http://cdn.prankerapp.com/prank-assets/DefaultPrankImage.jpg',
                'ord' => '1000',
                'data' => '{"_id":"59baa2d550a4fa001731be08","slug":"carmen","title":"Carmen","isInfluencer":false,"__v":0,"image":{"url":"http:\\/\\/cdn.prankerapp.com\\/prank-assets\\/DefaultPrankImage.jpg"}}',
                'created' => '2019-02-09 03:11:06',
                'modified' => '2020-07-01 06:51:46',
                'synced' => '2020-07-01 06:51:46',
            ],
            [
                'id' => '30',
                'ext_id' => '59cd4a9c74ad4300119d5aef',
                'status' => 'active',
                'slug' => 'mohammed-tarek',
                'title' => 'Mohammed Tarek',
                'is_influencer' => '1',
                'facebook_url' => 'https://www.facebook.com/mohammedtarektv/',
                'youtube_url' => 'https://www.youtube.com/user/RewinskyEver',
                'img_url' => 'http://cdn.prankerapp.com/prank-image/2Dg85ZuumvsZGHKn.png',
                'ord' => '1000',
                'data' => '{"_id":"59cd4a9c74ad4300119d5aef","slug":"mohammed-tarek","title":"Mohammed Tarek","isInfluencer":true,"__v":0,"facebookPageLink":"https:\\/\\/www.facebook.com\\/mohammedtarektv\\/","youtubeId":"RewinskyEver","image":{"mimetype":"image\\/png","size":78558,"filename":"2Dg85ZuumvsZGHKn.png","url":"http:\\/\\/cdn.prankerapp.com\\/prank-image\\/2Dg85ZuumvsZGHKn.png"}}',
                'created' => '2019-02-09 03:11:06',
                'modified' => '2020-07-01 06:54:03',
                'synced' => '2020-07-01 06:51:46',
            ],
            [
                'id' => '31',
                'ext_id' => '59fe4bd518e45c001179c658',
                'status' => 'active',
                'slug' => 'nelk',
                'title' => 'NELK',
                'is_influencer' => '1',
                'facebook_url' => 'https://www.facebook.com/Nelk/',
                'youtube_url' => 'https://www.youtube.com/user/NelkFilmz',
                'img_url' => 'http://cdn.prankerapp.com/prank-image/dIRFC3uStINaUcnG.png',
                'ord' => '1000',
                'data' => '{"_id":"59fe4bd518e45c001179c658","slug":"nelk","title":"NELK","isInfluencer":true,"__v":0,"facebookPageLink":"https:\\/\\/www.facebook.com\\/Nelk\\/","youtubeId":"NelkFilmz","image":{"mimetype":"image\\/png","size":5298,"filename":"dIRFC3uStINaUcnG.png","url":"http:\\/\\/cdn.prankerapp.com\\/prank-image\\/dIRFC3uStINaUcnG.png"},"description":"We prank people sometimes.."}',
                'created' => '2019-02-09 03:11:06',
                'modified' => '2020-07-01 06:53:25',
                'synced' => '2020-07-01 06:51:47',
            ],
            [
                'id' => '32',
                'ext_id' => '5a0b2c24429658001dbbadf7',
                'status' => 'active',
                'slug' => 'steve-o',
                'title' => 'Steve-O',
                'is_influencer' => '0',
                'facebook_url' => '',
                'youtube_url' => '',
                'img_url' => 'http://cdn.prankerapp.com/prank-assets/DefaultPrankImage.jpg',
                'ord' => '1000',
                'data' => '{"_id":"5a0b2c24429658001dbbadf7","slug":"steve-o","title":"Steve-O","isInfluencer":false,"__v":0,"description":"","image":{"url":"http:\\/\\/cdn.prankerapp.com\\/prank-assets\\/DefaultPrankImage.jpg"}}',
                'created' => '2019-02-09 03:11:07',
                'modified' => '2020-07-01 06:51:47',
                'synced' => '2020-07-01 06:51:47',
            ],
            [
                'id' => '33',
                'ext_id' => '5a706f8d64f4090019028d75',
                'status' => 'active',
                'slug' => 'alexander',
                'title' => 'Alexander',
                'is_influencer' => '0',
                'facebook_url' => '',
                'youtube_url' => '',
                'img_url' => 'http://cdn.prankerapp.com/prank-image/DNIrDgLKXwr8OGGZ.png',
                'ord' => '1000',
                'data' => '{"_id":"5a706f8d64f4090019028d75","slug":"alexander","title":"Alexander","isInfluencer":false,"__v":0,"description":"","image":{"mimetype":"image\\/png","size":49499,"filename":"DNIrDgLKXwr8OGGZ.png","url":"http:\\/\\/cdn.prankerapp.com\\/prank-image\\/DNIrDgLKXwr8OGGZ.png"}}',
                'created' => '2019-02-09 03:11:07',
                'modified' => '2020-07-01 06:53:20',
                'synced' => '2020-07-01 06:51:47',
            ],
            [
                'id' => '34',
                'ext_id' => '5d2ad126e3cae1001c581454',
                'status' => 'active',
                'slug' => 'irlrosie',
                'title' => 'IRLrosie',
                'is_influencer' => '0',
                'facebook_url' => '',
                'youtube_url' => '',
                'img_url' => 'http://cdn.prankerapp.com/prank-image/wdnLCUHj_tEfNKm2',
                'ord' => '1000',
                'data' => '{"_id":"5d2ad126e3cae1001c581454","slug":"irlrosie","title":"IRLrosie","isInfluencer":false,"image":{"mimetype":"image\\/png","filename":"wdnLCUHj_tEfNKm2","size":78501,"url":"http:\\/\\/cdn.prankerapp.com\\/prank-image\\/wdnLCUHj_tEfNKm2"},"__v":0,"description":""}',
                'created' => '2019-07-14 07:11:13',
                'modified' => '2020-07-01 06:53:23',
                'synced' => '2020-07-01 06:51:47',
            ],
            [
                'id' => '35',
                'ext_id' => '5d2ad5699215d0002a0185ba',
                'status' => 'active',
                'slug' => 'irlrosie-kourtney',
                'title' => 'IRLrosie Kourtney',
                'is_influencer' => '0',
                'facebook_url' => '',
                'youtube_url' => '',
                'img_url' => 'http://cdn.prankerapp.com/prank-image/oPurfWvTtaOsxcpr',
                'ord' => '1000',
                'data' => '{"_id":"5d2ad5699215d0002a0185ba","slug":"irlrosie-kourtney","title":"IRLrosie Kourtney","isInfluencer":false,"image":{"mimetype":"image\\/png","filename":"oPurfWvTtaOsxcpr","size":77450,"url":"http:\\/\\/cdn.prankerapp.com\\/prank-image\\/oPurfWvTtaOsxcpr"},"__v":0}',
                'created' => '2019-07-14 07:11:14',
                'modified' => '2020-07-01 06:53:23',
                'synced' => '2020-07-01 06:51:48',
            ],
            [
                'id' => '36',
                'ext_id' => '5e2edecef1be890015a3dc23',
                'status' => 'active',
                'slug' => 'mike',
                'title' => 'Mike',
                'is_influencer' => '0',
                'facebook_url' => '',
                'youtube_url' => '',
                'img_url' => 'http://cdn.prankerapp.com/prank-assets/DefaultPrankImage.jpg',
                'ord' => '1000',
                'data' => '{"_id":"5e2edecef1be890015a3dc23","slug":"mike","title":"Mike","isInfluencer":false,"__v":0,"image":{"url":"http:\\/\\/cdn.prankerapp.com\\/prank-assets\\/DefaultPrankImage.jpg"}}',
                'created' => '2020-01-28 07:11:12',
                'modified' => '2020-07-01 06:53:46',
                'synced' => '2020-07-01 06:51:48',
            ],
            [
                'id' => '37',
                'ext_id' => '5e8368d2dc15c4002b2e564b',
                'status' => 'active',
                'slug' => 'sylvie-quebec',
                'title' => 'Sylvie (Québec) ',
                'is_influencer' => '0',
                'facebook_url' => '',
                'youtube_url' => '',
                'img_url' => 'http://cdn.prankerapp.com/prank-assets/DefaultPrankImage.jpg',
                'ord' => '1000',
                'data' => '{"_id":"5e8368d2dc15c4002b2e564b","slug":"sylvie-quebec","title":"Sylvie (Qu\\u00e9bec) ","isInfluencer":false,"__v":0,"description":"","image":{"url":"http:\\/\\/cdn.prankerapp.com\\/prank-assets\\/DefaultPrankImage.jpg"}}',
                'created' => '2020-04-08 06:47:32',
                'modified' => '2020-07-01 06:54:05',
                'synced' => '2020-07-01 06:51:48',
            ],
            [
                'id' => '38',
                'ext_id' => '5e85ebf179d7380023c1300c',
                'status' => 'active',
                'slug' => 'lola-france',
                'title' => 'Lola (France)',
                'is_influencer' => '0',
                'facebook_url' => '',
                'youtube_url' => '',
                'img_url' => 'http://cdn.prankerapp.com/prank-assets/DefaultPrankImage.jpg',
                'ord' => '1000',
                'data' => '{"_id":"5e85ebf179d7380023c1300c","slug":"lola-france","title":"Lola (France)","isInfluencer":false,"__v":0,"description":"","image":{"url":"http:\\/\\/cdn.prankerapp.com\\/prank-assets\\/DefaultPrankImage.jpg"}}',
                'created' => '2020-04-08 06:47:32',
                'modified' => '2020-07-01 06:54:12',
                'synced' => '2020-07-01 06:51:48',
            ],
            [
                'id' => '39',
                'ext_id' => '5e99eb004549100024748a94',
                'status' => 'active',
                'slug' => 'pranker',
                'title' => 'Pranker',
                'is_influencer' => '0',
                'facebook_url' => '',
                'youtube_url' => '',
                'img_url' => 'http://cdn.prankerapp.com/prank-assets/DefaultPrankImage.jpg',
                'ord' => '1000',
                'data' => '{"_id":"5e99eb004549100024748a94","slug":"pranker","title":"Pranker","isInfluencer":false,"__v":0,"description":"","image":{"url":"http:\\/\\/cdn.prankerapp.com\\/prank-assets\\/DefaultPrankImage.jpg"}}',
                'created' => '2020-07-01 06:51:48',
                'modified' => '2020-07-01 06:53:42',
                'synced' => '2020-07-01 06:51:48',
            ],
        ];

        $table = $this->table('app_characters');
        $table->insert($data)->save();
    }
}
