<?php
use Migrations\AbstractSeed;

/**
 * AppPrankScriptsAppCharacters seed.
 */
class AppPrankScriptsAppCharactersSeed extends AbstractSeed
{
    /**
     * Run Method.
     *
     * Write your database seeder using this method.
     *
     * More information on writing seeds is available here:
     * https://book.cakephp.org/phinx/0/en/seeding.html
     *
     * @return void
     */
    public function run()
    {
        $data = [
            [
                'id' => '18',
                'app_prank_script_id' => '73',
                'app_character_id' => '22',
                'is_default' => '1',
            ],
            [
                'id' => '1246',
                'app_prank_script_id' => '67',
                'app_character_id' => '26',
                'is_default' => '1',
            ],
            [
                'id' => '1247',
                'app_prank_script_id' => '68',
                'app_character_id' => '17',
                'is_default' => '1',
            ],
            [
                'id' => '1248',
                'app_prank_script_id' => '43',
                'app_character_id' => '16',
                'is_default' => '1',
            ],
            [
                'id' => '1249',
                'app_prank_script_id' => '46',
                'app_character_id' => '16',
                'is_default' => '1',
            ],
            [
                'id' => '1250',
                'app_prank_script_id' => '44',
                'app_character_id' => '11',
                'is_default' => '1',
            ],
            [
                'id' => '1251',
                'app_prank_script_id' => '20',
                'app_character_id' => '1',
                'is_default' => '1',
            ],
            [
                'id' => '1252',
                'app_prank_script_id' => '17',
                'app_character_id' => '27',
                'is_default' => '1',
            ],
            [
                'id' => '1253',
                'app_prank_script_id' => '33',
                'app_character_id' => '14',
                'is_default' => '1',
            ],
            [
                'id' => '1254',
                'app_prank_script_id' => '69',
                'app_character_id' => '17',
                'is_default' => '1',
            ],
            [
                'id' => '1255',
                'app_prank_script_id' => '27',
                'app_character_id' => '27',
                'is_default' => '1',
            ],
            [
                'id' => '1256',
                'app_prank_script_id' => '26',
                'app_character_id' => '27',
                'is_default' => '1',
            ],
            [
                'id' => '1257',
                'app_prank_script_id' => '24',
                'app_character_id' => '10',
                'is_default' => '1',
            ],
            [
                'id' => '1258',
                'app_prank_script_id' => '70',
                'app_character_id' => '9',
                'is_default' => '1',
            ],
            [
                'id' => '1259',
                'app_prank_script_id' => '9',
                'app_character_id' => '3',
                'is_default' => '1',
            ],
            [
                'id' => '1260',
                'app_prank_script_id' => '13',
                'app_character_id' => '12',
                'is_default' => '1',
            ],
            [
                'id' => '1261',
                'app_prank_script_id' => '71',
                'app_character_id' => '17',
                'is_default' => '1',
            ],
            [
                'id' => '1262',
                'app_prank_script_id' => '72',
                'app_character_id' => '14',
                'is_default' => '1',
            ],
            [
                'id' => '1264',
                'app_prank_script_id' => '16',
                'app_character_id' => '1',
                'is_default' => '1',
            ],
            [
                'id' => '1265',
                'app_prank_script_id' => '74',
                'app_character_id' => '33',
                'is_default' => '1',
            ],
            [
                'id' => '1266',
                'app_prank_script_id' => '3',
                'app_character_id' => '24',
                'is_default' => '1',
            ],
            [
                'id' => '1267',
                'app_prank_script_id' => '75',
                'app_character_id' => '10',
                'is_default' => '1',
            ],
            [
                'id' => '1268',
                'app_prank_script_id' => '76',
                'app_character_id' => '10',
                'is_default' => '1',
            ],
            [
                'id' => '1269',
                'app_prank_script_id' => '28',
                'app_character_id' => '17',
                'is_default' => '1',
            ],
            [
                'id' => '1270',
                'app_prank_script_id' => '77',
                'app_character_id' => '6',
                'is_default' => '1',
            ],
            [
                'id' => '1271',
                'app_prank_script_id' => '78',
                'app_character_id' => '7',
                'is_default' => '1',
            ],
            [
                'id' => '1272',
                'app_prank_script_id' => '15',
                'app_character_id' => '10',
                'is_default' => '1',
            ],
            [
                'id' => '1273',
                'app_prank_script_id' => '79',
                'app_character_id' => '10',
                'is_default' => '1',
            ],
            [
                'id' => '1274',
                'app_prank_script_id' => '21',
                'app_character_id' => '8',
                'is_default' => '1',
            ],
            [
                'id' => '1275',
                'app_prank_script_id' => '47',
                'app_character_id' => '11',
                'is_default' => '1',
            ],
            [
                'id' => '1276',
                'app_prank_script_id' => '45',
                'app_character_id' => '25',
                'is_default' => '1',
            ],
            [
                'id' => '1277',
                'app_prank_script_id' => '80',
                'app_character_id' => '16',
                'is_default' => '1',
            ],
            [
                'id' => '1278',
                'app_prank_script_id' => '25',
                'app_character_id' => '17',
                'is_default' => '1',
            ],
            [
                'id' => '1279',
                'app_prank_script_id' => '39',
                'app_character_id' => '16',
                'is_default' => '1',
            ],
            [
                'id' => '1280',
                'app_prank_script_id' => '7',
                'app_character_id' => '18',
                'is_default' => '1',
            ],
            [
                'id' => '1281',
                'app_prank_script_id' => '2',
                'app_character_id' => '18',
                'is_default' => '1',
            ],
            [
                'id' => '1282',
                'app_prank_script_id' => '14',
                'app_character_id' => '31',
                'is_default' => '1',
            ],
            [
                'id' => '1283',
                'app_prank_script_id' => '42',
                'app_character_id' => '16',
                'is_default' => '1',
            ],
            [
                'id' => '1284',
                'app_prank_script_id' => '81',
                'app_character_id' => '1',
                'is_default' => '1',
            ],
            [
                'id' => '1285',
                'app_prank_script_id' => '82',
                'app_character_id' => '26',
                'is_default' => '1',
            ],
            [
                'id' => '1286',
                'app_prank_script_id' => '6',
                'app_character_id' => '18',
                'is_default' => '1',
            ],
            [
                'id' => '1287',
                'app_prank_script_id' => '32',
                'app_character_id' => '27',
                'is_default' => '1',
            ],
            [
                'id' => '1288',
                'app_prank_script_id' => '31',
                'app_character_id' => '27',
                'is_default' => '1',
            ],
            [
                'id' => '1289',
                'app_prank_script_id' => '30',
                'app_character_id' => '27',
                'is_default' => '1',
            ],
            [
                'id' => '1290',
                'app_prank_script_id' => '5',
                'app_character_id' => '18',
                'is_default' => '1',
            ],
            [
                'id' => '1291',
                'app_prank_script_id' => '83',
                'app_character_id' => '17',
                'is_default' => '1',
            ],
            [
                'id' => '1292',
                'app_prank_script_id' => '11',
                'app_character_id' => '10',
                'is_default' => '1',
            ],
            [
                'id' => '1293',
                'app_prank_script_id' => '84',
                'app_character_id' => '17',
                'is_default' => '1',
            ],
            [
                'id' => '1294',
                'app_prank_script_id' => '22',
                'app_character_id' => '8',
                'is_default' => '1',
            ],
            [
                'id' => '1295',
                'app_prank_script_id' => '41',
                'app_character_id' => '27',
                'is_default' => '1',
            ],
            [
                'id' => '1296',
                'app_prank_script_id' => '51',
                'app_character_id' => '15',
                'is_default' => '1',
            ],
            [
                'id' => '1297',
                'app_prank_script_id' => '19',
                'app_character_id' => '17',
                'is_default' => '1',
            ],
            [
                'id' => '1298',
                'app_prank_script_id' => '4',
                'app_character_id' => '18',
                'is_default' => '1',
            ],
            [
                'id' => '1299',
                'app_prank_script_id' => '38',
                'app_character_id' => '3',
                'is_default' => '1',
            ],
            [
                'id' => '1300',
                'app_prank_script_id' => '18',
                'app_character_id' => '3',
                'is_default' => '1',
            ],
            [
                'id' => '1301',
                'app_prank_script_id' => '36',
                'app_character_id' => '12',
                'is_default' => '1',
            ],
            [
                'id' => '1302',
                'app_prank_script_id' => '52',
                'app_character_id' => '8',
                'is_default' => '1',
            ],
            [
                'id' => '1303',
                'app_prank_script_id' => '40',
                'app_character_id' => '27',
                'is_default' => '1',
            ],
            [
                'id' => '1304',
                'app_prank_script_id' => '23',
                'app_character_id' => '27',
                'is_default' => '1',
            ],
            [
                'id' => '1305',
                'app_prank_script_id' => '35',
                'app_character_id' => '3',
                'is_default' => '1',
            ],
            [
                'id' => '1306',
                'app_prank_script_id' => '37',
                'app_character_id' => '20',
                'is_default' => '1',
            ],
            [
                'id' => '1307',
                'app_prank_script_id' => '53',
                'app_character_id' => '14',
                'is_default' => '1',
            ],
            [
                'id' => '1308',
                'app_prank_script_id' => '1',
                'app_character_id' => '10',
                'is_default' => '1',
            ],
            [
                'id' => '1309',
                'app_prank_script_id' => '12',
                'app_character_id' => '5',
                'is_default' => '1',
            ],
            [
                'id' => '1310',
                'app_prank_script_id' => '29',
                'app_character_id' => '27',
                'is_default' => '1',
            ],
            [
                'id' => '1311',
                'app_prank_script_id' => '48',
                'app_character_id' => '27',
                'is_default' => '1',
            ],
            [
                'id' => '1312',
                'app_prank_script_id' => '50',
                'app_character_id' => '27',
                'is_default' => '1',
            ],
            [
                'id' => '1313',
                'app_prank_script_id' => '54',
                'app_character_id' => '16',
                'is_default' => '1',
            ],
            [
                'id' => '1314',
                'app_prank_script_id' => '8',
                'app_character_id' => '18',
                'is_default' => '1',
            ],
            [
                'id' => '1315',
                'app_prank_script_id' => '55',
                'app_character_id' => '17',
                'is_default' => '1',
            ],
            [
                'id' => '1316',
                'app_prank_script_id' => '56',
                'app_character_id' => '14',
                'is_default' => '1',
            ],
            [
                'id' => '1317',
                'app_prank_script_id' => '58',
                'app_character_id' => '8',
                'is_default' => '1',
            ],
            [
                'id' => '1318',
                'app_prank_script_id' => '59',
                'app_character_id' => '26',
                'is_default' => '1',
            ],
            [
                'id' => '1319',
                'app_prank_script_id' => '60',
                'app_character_id' => '10',
                'is_default' => '1',
            ],
            [
                'id' => '1320',
                'app_prank_script_id' => '34',
                'app_character_id' => '3',
                'is_default' => '1',
            ],
            [
                'id' => '1321',
                'app_prank_script_id' => '61',
                'app_character_id' => '3',
                'is_default' => '1',
            ],
            [
                'id' => '1322',
                'app_prank_script_id' => '62',
                'app_character_id' => '10',
                'is_default' => '1',
            ],
            [
                'id' => '1323',
                'app_prank_script_id' => '63',
                'app_character_id' => '17',
                'is_default' => '1',
            ],
            [
                'id' => '1324',
                'app_prank_script_id' => '64',
                'app_character_id' => '17',
                'is_default' => '1',
            ],
            [
                'id' => '1325',
                'app_prank_script_id' => '10',
                'app_character_id' => '10',
                'is_default' => '1',
            ],
            [
                'id' => '1326',
                'app_prank_script_id' => '49',
                'app_character_id' => '10',
                'is_default' => '1',
            ],
            [
                'id' => '1327',
                'app_prank_script_id' => '65',
                'app_character_id' => '10',
                'is_default' => '1',
            ],
            [
                'id' => '1328',
                'app_prank_script_id' => '66',
                'app_character_id' => '23',
                'is_default' => '1',
            ],
            [
                'id' => '1329',
                'app_prank_script_id' => '13',
                'app_character_id' => '10',
                'is_default' => '0',
            ],
            [
                'id' => '1331',
                'app_prank_script_id' => '80',
                'app_character_id' => '31',
                'is_default' => '0',
            ],
            [
                'id' => '1332',
                'app_prank_script_id' => '5',
                'app_character_id' => '3',
                'is_default' => '0',
            ],
            [
                'id' => '1334',
                'app_prank_script_id' => '52',
                'app_character_id' => '10',
                'is_default' => '0',
            ],
            [
                'id' => '1335',
                'app_prank_script_id' => '52',
                'app_character_id' => '16',
                'is_default' => '0',
            ],
            [
                'id' => '1336',
                'app_prank_script_id' => '23',
                'app_character_id' => '10',
                'is_default' => '0',
            ],
            [
                'id' => '1337',
                'app_prank_script_id' => '23',
                'app_character_id' => '16',
                'is_default' => '0',
            ],
            [
                'id' => '1338',
                'app_prank_script_id' => '1',
                'app_character_id' => '4',
                'is_default' => '0',
            ],
            [
                'id' => '1339',
                'app_prank_script_id' => '1',
                'app_character_id' => '13',
                'is_default' => '0',
            ],
            [
                'id' => '1340',
                'app_prank_script_id' => '1',
                'app_character_id' => '31',
                'is_default' => '0',
            ],
            [
                'id' => '1341',
                'app_prank_script_id' => '29',
                'app_character_id' => '10',
                'is_default' => '0',
            ],
            [
                'id' => '1343',
                'app_prank_script_id' => '48',
                'app_character_id' => '13',
                'is_default' => '0',
            ],
            [
                'id' => '1345',
                'app_prank_script_id' => '48',
                'app_character_id' => '31',
                'is_default' => '0',
            ],
            [
                'id' => '1346',
                'app_prank_script_id' => '50',
                'app_character_id' => '17',
                'is_default' => '0',
            ],
            [
                'id' => '1347',
                'app_prank_script_id' => '57',
                'app_character_id' => '27',
                'is_default' => '0',
            ],
            [
                'id' => '1348',
                'app_prank_script_id' => '57',
                'app_character_id' => '17',
                'is_default' => '0',
            ],
            [
                'id' => '1349',
                'app_prank_script_id' => '34',
                'app_character_id' => '30',
                'is_default' => '0',
            ],
            [
                'id' => '1350',
                'app_prank_script_id' => '61',
                'app_character_id' => '27',
                'is_default' => '0',
            ],
            [
                'id' => '1365',
                'app_prank_script_id' => '85',
                'app_character_id' => '22',
                'is_default' => '1',
            ],
            [
                'id' => '1366',
                'app_prank_script_id' => '86',
                'app_character_id' => '22',
                'is_default' => '1',
            ],
            [
                'id' => '1367',
                'app_prank_script_id' => '87',
                'app_character_id' => '22',
                'is_default' => '1',
            ],
            [
                'id' => '1368',
                'app_prank_script_id' => '88',
                'app_character_id' => '34',
                'is_default' => '1',
            ],
            [
                'id' => '1369',
                'app_prank_script_id' => '89',
                'app_character_id' => '34',
                'is_default' => '1',
            ],
            [
                'id' => '1370',
                'app_prank_script_id' => '89',
                'app_character_id' => '35',
                'is_default' => '0',
            ],
            [
                'id' => '1399',
                'app_prank_script_id' => '118',
                'app_character_id' => '22',
                'is_default' => '1',
            ],
            [
                'id' => '1400',
                'app_prank_script_id' => '119',
                'app_character_id' => '22',
                'is_default' => '1',
            ],
            [
                'id' => '1401',
                'app_prank_script_id' => '120',
                'app_character_id' => '22',
                'is_default' => '1',
            ],
            [
                'id' => '1402',
                'app_prank_script_id' => '121',
                'app_character_id' => '22',
                'is_default' => '1',
            ],
            [
                'id' => '1403',
                'app_prank_script_id' => '122',
                'app_character_id' => '22',
                'is_default' => '1',
            ],
            [
                'id' => '1404',
                'app_prank_script_id' => '123',
                'app_character_id' => '22',
                'is_default' => '1',
            ],
            [
                'id' => '1405',
                'app_prank_script_id' => '124',
                'app_character_id' => '22',
                'is_default' => '1',
            ],
            [
                'id' => '1406',
                'app_prank_script_id' => '125',
                'app_character_id' => '22',
                'is_default' => '1',
            ],
            [
                'id' => '1407',
                'app_prank_script_id' => '126',
                'app_character_id' => '22',
                'is_default' => '1',
            ],
            [
                'id' => '1408',
                'app_prank_script_id' => '127',
                'app_character_id' => '22',
                'is_default' => '1',
            ],
            [
                'id' => '1409',
                'app_prank_script_id' => '128',
                'app_character_id' => '22',
                'is_default' => '1',
            ],
            [
                'id' => '1410',
                'app_prank_script_id' => '129',
                'app_character_id' => '22',
                'is_default' => '1',
            ],
            [
                'id' => '1411',
                'app_prank_script_id' => '130',
                'app_character_id' => '22',
                'is_default' => '1',
            ],
            [
                'id' => '1412',
                'app_prank_script_id' => '131',
                'app_character_id' => '22',
                'is_default' => '1',
            ],
            [
                'id' => '1413',
                'app_prank_script_id' => '132',
                'app_character_id' => '22',
                'is_default' => '1',
            ],
            [
                'id' => '1414',
                'app_prank_script_id' => '133',
                'app_character_id' => '22',
                'is_default' => '1',
            ],
            [
                'id' => '1415',
                'app_prank_script_id' => '134',
                'app_character_id' => '22',
                'is_default' => '1',
            ],
            [
                'id' => '1416',
                'app_prank_script_id' => '135',
                'app_character_id' => '22',
                'is_default' => '1',
            ],
            [
                'id' => '1417',
                'app_prank_script_id' => '136',
                'app_character_id' => '22',
                'is_default' => '1',
            ],
            [
                'id' => '1418',
                'app_prank_script_id' => '137',
                'app_character_id' => '22',
                'is_default' => '1',
            ],
            [
                'id' => '1419',
                'app_prank_script_id' => '138',
                'app_character_id' => '22',
                'is_default' => '1',
            ],
            [
                'id' => '1420',
                'app_prank_script_id' => '139',
                'app_character_id' => '22',
                'is_default' => '1',
            ],
            [
                'id' => '1421',
                'app_prank_script_id' => '140',
                'app_character_id' => '22',
                'is_default' => '1',
            ],
            [
                'id' => '1422',
                'app_prank_script_id' => '141',
                'app_character_id' => '22',
                'is_default' => '1',
            ],
            [
                'id' => '1423',
                'app_prank_script_id' => '142',
                'app_character_id' => '22',
                'is_default' => '1',
            ],
            [
                'id' => '1424',
                'app_prank_script_id' => '143',
                'app_character_id' => '22',
                'is_default' => '1',
            ],
            [
                'id' => '1425',
                'app_prank_script_id' => '144',
                'app_character_id' => '22',
                'is_default' => '1',
            ],
            [
                'id' => '1426',
                'app_prank_script_id' => '145',
                'app_character_id' => '22',
                'is_default' => '1',
            ],
            [
                'id' => '1427',
                'app_prank_script_id' => '146',
                'app_character_id' => '22',
                'is_default' => '1',
            ],
            [
                'id' => '1428',
                'app_prank_script_id' => '147',
                'app_character_id' => '22',
                'is_default' => '1',
            ],
            [
                'id' => '1429',
                'app_prank_script_id' => '148',
                'app_character_id' => '22',
                'is_default' => '1',
            ],
            [
                'id' => '1430',
                'app_prank_script_id' => '149',
                'app_character_id' => '22',
                'is_default' => '1',
            ],
            [
                'id' => '1431',
                'app_prank_script_id' => '150',
                'app_character_id' => '22',
                'is_default' => '1',
            ],
            [
                'id' => '1432',
                'app_prank_script_id' => '151',
                'app_character_id' => '22',
                'is_default' => '1',
            ],
            [
                'id' => '1433',
                'app_prank_script_id' => '152',
                'app_character_id' => '22',
                'is_default' => '1',
            ],
            [
                'id' => '1434',
                'app_prank_script_id' => '153',
                'app_character_id' => '22',
                'is_default' => '1',
            ],
            [
                'id' => '1435',
                'app_prank_script_id' => '154',
                'app_character_id' => '22',
                'is_default' => '1',
            ],
            [
                'id' => '1436',
                'app_prank_script_id' => '155',
                'app_character_id' => '22',
                'is_default' => '1',
            ],
            [
                'id' => '1437',
                'app_prank_script_id' => '156',
                'app_character_id' => '22',
                'is_default' => '1',
            ],
            [
                'id' => '1438',
                'app_prank_script_id' => '157',
                'app_character_id' => '22',
                'is_default' => '1',
            ],
            [
                'id' => '1439',
                'app_prank_script_id' => '158',
                'app_character_id' => '22',
                'is_default' => '1',
            ],
            [
                'id' => '1440',
                'app_prank_script_id' => '159',
                'app_character_id' => '22',
                'is_default' => '1',
            ],
            [
                'id' => '1441',
                'app_prank_script_id' => '160',
                'app_character_id' => '22',
                'is_default' => '1',
            ],
            [
                'id' => '1442',
                'app_prank_script_id' => '161',
                'app_character_id' => '22',
                'is_default' => '1',
            ],
            [
                'id' => '1443',
                'app_prank_script_id' => '162',
                'app_character_id' => '22',
                'is_default' => '1',
            ],
            [
                'id' => '1444',
                'app_prank_script_id' => '163',
                'app_character_id' => '22',
                'is_default' => '1',
            ],
            [
                'id' => '1445',
                'app_prank_script_id' => '164',
                'app_character_id' => '22',
                'is_default' => '1',
            ],
            [
                'id' => '1446',
                'app_prank_script_id' => '165',
                'app_character_id' => '22',
                'is_default' => '1',
            ],
            [
                'id' => '1447',
                'app_prank_script_id' => '166',
                'app_character_id' => '22',
                'is_default' => '1',
            ],
            [
                'id' => '1448',
                'app_prank_script_id' => '167',
                'app_character_id' => '22',
                'is_default' => '1',
            ],
            [
                'id' => '1449',
                'app_prank_script_id' => '168',
                'app_character_id' => '22',
                'is_default' => '1',
            ],
            [
                'id' => '1450',
                'app_prank_script_id' => '169',
                'app_character_id' => '22',
                'is_default' => '1',
            ],
            [
                'id' => '1451',
                'app_prank_script_id' => '170',
                'app_character_id' => '22',
                'is_default' => '1',
            ],
            [
                'id' => '1452',
                'app_prank_script_id' => '171',
                'app_character_id' => '22',
                'is_default' => '1',
            ],
            [
                'id' => '1453',
                'app_prank_script_id' => '172',
                'app_character_id' => '22',
                'is_default' => '1',
            ],
            [
                'id' => '1454',
                'app_prank_script_id' => '173',
                'app_character_id' => '22',
                'is_default' => '1',
            ],
            [
                'id' => '1455',
                'app_prank_script_id' => '174',
                'app_character_id' => '22',
                'is_default' => '1',
            ],
            [
                'id' => '1456',
                'app_prank_script_id' => '175',
                'app_character_id' => '22',
                'is_default' => '1',
            ],
            [
                'id' => '1457',
                'app_prank_script_id' => '176',
                'app_character_id' => '22',
                'is_default' => '1',
            ],
            [
                'id' => '1458',
                'app_prank_script_id' => '177',
                'app_character_id' => '22',
                'is_default' => '1',
            ],
            [
                'id' => '1459',
                'app_prank_script_id' => '178',
                'app_character_id' => '22',
                'is_default' => '1',
            ],
            [
                'id' => '1460',
                'app_prank_script_id' => '179',
                'app_character_id' => '22',
                'is_default' => '1',
            ],
            [
                'id' => '1461',
                'app_prank_script_id' => '180',
                'app_character_id' => '22',
                'is_default' => '1',
            ],
            [
                'id' => '1462',
                'app_prank_script_id' => '181',
                'app_character_id' => '22',
                'is_default' => '1',
            ],
            [
                'id' => '1463',
                'app_prank_script_id' => '182',
                'app_character_id' => '22',
                'is_default' => '1',
            ],
            [
                'id' => '1464',
                'app_prank_script_id' => '183',
                'app_character_id' => '22',
                'is_default' => '1',
            ],
            [
                'id' => '1465',
                'app_prank_script_id' => '184',
                'app_character_id' => '22',
                'is_default' => '1',
            ],
            [
                'id' => '1466',
                'app_prank_script_id' => '185',
                'app_character_id' => '22',
                'is_default' => '1',
            ],
            [
                'id' => '1467',
                'app_prank_script_id' => '186',
                'app_character_id' => '22',
                'is_default' => '1',
            ],
            [
                'id' => '1468',
                'app_prank_script_id' => '187',
                'app_character_id' => '22',
                'is_default' => '1',
            ],
            [
                'id' => '1469',
                'app_prank_script_id' => '188',
                'app_character_id' => '22',
                'is_default' => '1',
            ],
            [
                'id' => '1470',
                'app_prank_script_id' => '189',
                'app_character_id' => '22',
                'is_default' => '1',
            ],
            [
                'id' => '1471',
                'app_prank_script_id' => '190',
                'app_character_id' => '22',
                'is_default' => '1',
            ],
            [
                'id' => '1472',
                'app_prank_script_id' => '191',
                'app_character_id' => '22',
                'is_default' => '1',
            ],
            [
                'id' => '1473',
                'app_prank_script_id' => '192',
                'app_character_id' => '22',
                'is_default' => '1',
            ],
            [
                'id' => '1474',
                'app_prank_script_id' => '193',
                'app_character_id' => '22',
                'is_default' => '1',
            ],
            [
                'id' => '1475',
                'app_prank_script_id' => '194',
                'app_character_id' => '22',
                'is_default' => '1',
            ],
            [
                'id' => '1476',
                'app_prank_script_id' => '195',
                'app_character_id' => '22',
                'is_default' => '1',
            ],
            [
                'id' => '1477',
                'app_prank_script_id' => '196',
                'app_character_id' => '22',
                'is_default' => '1',
            ],
            [
                'id' => '1478',
                'app_prank_script_id' => '197',
                'app_character_id' => '22',
                'is_default' => '1',
            ],
            [
                'id' => '1479',
                'app_prank_script_id' => '198',
                'app_character_id' => '22',
                'is_default' => '1',
            ],
            [
                'id' => '1480',
                'app_prank_script_id' => '199',
                'app_character_id' => '22',
                'is_default' => '1',
            ],
            [
                'id' => '1481',
                'app_prank_script_id' => '200',
                'app_character_id' => '22',
                'is_default' => '1',
            ],
            [
                'id' => '1482',
                'app_prank_script_id' => '201',
                'app_character_id' => '22',
                'is_default' => '1',
            ],
            [
                'id' => '1483',
                'app_prank_script_id' => '202',
                'app_character_id' => '22',
                'is_default' => '1',
            ],
            [
                'id' => '1484',
                'app_prank_script_id' => '203',
                'app_character_id' => '22',
                'is_default' => '1',
            ],
            [
                'id' => '1485',
                'app_prank_script_id' => '204',
                'app_character_id' => '22',
                'is_default' => '1',
            ],
            [
                'id' => '1486',
                'app_prank_script_id' => '205',
                'app_character_id' => '22',
                'is_default' => '1',
            ],
            [
                'id' => '1487',
                'app_prank_script_id' => '206',
                'app_character_id' => '22',
                'is_default' => '1',
            ],
            [
                'id' => '1488',
                'app_prank_script_id' => '207',
                'app_character_id' => '22',
                'is_default' => '1',
            ],
            [
                'id' => '1489',
                'app_prank_script_id' => '208',
                'app_character_id' => '22',
                'is_default' => '1',
            ],
            [
                'id' => '1490',
                'app_prank_script_id' => '209',
                'app_character_id' => '22',
                'is_default' => '1',
            ],
            [
                'id' => '1491',
                'app_prank_script_id' => '210',
                'app_character_id' => '22',
                'is_default' => '1',
            ],
            [
                'id' => '1492',
                'app_prank_script_id' => '211',
                'app_character_id' => '22',
                'is_default' => '1',
            ],
            [
                'id' => '1493',
                'app_prank_script_id' => '212',
                'app_character_id' => '22',
                'is_default' => '1',
            ],
            [
                'id' => '1524',
                'app_prank_script_id' => '243',
                'app_character_id' => '22',
                'is_default' => '1',
            ],
            [
                'id' => '1525',
                'app_prank_script_id' => '244',
                'app_character_id' => '22',
                'is_default' => '1',
            ],
            [
                'id' => '1526',
                'app_prank_script_id' => '245',
                'app_character_id' => '22',
                'is_default' => '1',
            ],
            [
                'id' => '1527',
                'app_prank_script_id' => '246',
                'app_character_id' => '22',
                'is_default' => '1',
            ],
            [
                'id' => '1528',
                'app_prank_script_id' => '247',
                'app_character_id' => '22',
                'is_default' => '1',
            ],
            [
                'id' => '1529',
                'app_prank_script_id' => '248',
                'app_character_id' => '22',
                'is_default' => '1',
            ],
            [
                'id' => '1530',
                'app_prank_script_id' => '249',
                'app_character_id' => '22',
                'is_default' => '1',
            ],
            [
                'id' => '1531',
                'app_prank_script_id' => '250',
                'app_character_id' => '22',
                'is_default' => '1',
            ],
            [
                'id' => '1532',
                'app_prank_script_id' => '251',
                'app_character_id' => '22',
                'is_default' => '1',
            ],
            [
                'id' => '1533',
                'app_prank_script_id' => '252',
                'app_character_id' => '22',
                'is_default' => '1',
            ],
            [
                'id' => '1534',
                'app_prank_script_id' => '253',
                'app_character_id' => '22',
                'is_default' => '1',
            ],
            [
                'id' => '1535',
                'app_prank_script_id' => '254',
                'app_character_id' => '22',
                'is_default' => '1',
            ],
            [
                'id' => '1536',
                'app_prank_script_id' => '255',
                'app_character_id' => '22',
                'is_default' => '1',
            ],
            [
                'id' => '1537',
                'app_prank_script_id' => '256',
                'app_character_id' => '22',
                'is_default' => '1',
            ],
            [
                'id' => '1538',
                'app_prank_script_id' => '257',
                'app_character_id' => '22',
                'is_default' => '1',
            ],
            [
                'id' => '1539',
                'app_prank_script_id' => '258',
                'app_character_id' => '22',
                'is_default' => '1',
            ],
            [
                'id' => '1540',
                'app_prank_script_id' => '259',
                'app_character_id' => '22',
                'is_default' => '1',
            ],
            [
                'id' => '1541',
                'app_prank_script_id' => '260',
                'app_character_id' => '22',
                'is_default' => '1',
            ],
            [
                'id' => '1542',
                'app_prank_script_id' => '261',
                'app_character_id' => '22',
                'is_default' => '1',
            ],
            [
                'id' => '1543',
                'app_prank_script_id' => '262',
                'app_character_id' => '22',
                'is_default' => '1',
            ],
            [
                'id' => '1544',
                'app_prank_script_id' => '263',
                'app_character_id' => '22',
                'is_default' => '1',
            ],
            [
                'id' => '1545',
                'app_prank_script_id' => '264',
                'app_character_id' => '22',
                'is_default' => '1',
            ],
            [
                'id' => '1546',
                'app_prank_script_id' => '265',
                'app_character_id' => '22',
                'is_default' => '1',
            ],
            [
                'id' => '1547',
                'app_prank_script_id' => '266',
                'app_character_id' => '22',
                'is_default' => '1',
            ],
            [
                'id' => '1548',
                'app_prank_script_id' => '267',
                'app_character_id' => '22',
                'is_default' => '1',
            ],
            [
                'id' => '1549',
                'app_prank_script_id' => '268',
                'app_character_id' => '22',
                'is_default' => '1',
            ],
            [
                'id' => '1550',
                'app_prank_script_id' => '269',
                'app_character_id' => '22',
                'is_default' => '1',
            ],
            [
                'id' => '1551',
                'app_prank_script_id' => '270',
                'app_character_id' => '22',
                'is_default' => '1',
            ],
            [
                'id' => '1552',
                'app_prank_script_id' => '271',
                'app_character_id' => '22',
                'is_default' => '1',
            ],
            [
                'id' => '1553',
                'app_prank_script_id' => '272',
                'app_character_id' => '22',
                'is_default' => '1',
            ],
            [
                'id' => '1554',
                'app_prank_script_id' => '273',
                'app_character_id' => '22',
                'is_default' => '1',
            ],
            [
                'id' => '1555',
                'app_prank_script_id' => '274',
                'app_character_id' => '22',
                'is_default' => '1',
            ],
            [
                'id' => '1556',
                'app_prank_script_id' => '275',
                'app_character_id' => '22',
                'is_default' => '1',
            ],
            [
                'id' => '1557',
                'app_prank_script_id' => '276',
                'app_character_id' => '22',
                'is_default' => '1',
            ],
            [
                'id' => '1558',
                'app_prank_script_id' => '277',
                'app_character_id' => '22',
                'is_default' => '1',
            ],
            [
                'id' => '1559',
                'app_prank_script_id' => '278',
                'app_character_id' => '22',
                'is_default' => '1',
            ],
            [
                'id' => '1560',
                'app_prank_script_id' => '279',
                'app_character_id' => '22',
                'is_default' => '1',
            ],
            [
                'id' => '1561',
                'app_prank_script_id' => '280',
                'app_character_id' => '22',
                'is_default' => '1',
            ],
            [
                'id' => '1562',
                'app_prank_script_id' => '281',
                'app_character_id' => '22',
                'is_default' => '1',
            ],
            [
                'id' => '1563',
                'app_prank_script_id' => '282',
                'app_character_id' => '22',
                'is_default' => '1',
            ],
            [
                'id' => '1564',
                'app_prank_script_id' => '283',
                'app_character_id' => '22',
                'is_default' => '1',
            ],
            [
                'id' => '1565',
                'app_prank_script_id' => '284',
                'app_character_id' => '22',
                'is_default' => '1',
            ],
            [
                'id' => '1566',
                'app_prank_script_id' => '285',
                'app_character_id' => '22',
                'is_default' => '1',
            ],
            [
                'id' => '1567',
                'app_prank_script_id' => '286',
                'app_character_id' => '22',
                'is_default' => '1',
            ],
            [
                'id' => '1568',
                'app_prank_script_id' => '287',
                'app_character_id' => '22',
                'is_default' => '1',
            ],
            [
                'id' => '1569',
                'app_prank_script_id' => '288',
                'app_character_id' => '22',
                'is_default' => '1',
            ],
            [
                'id' => '1570',
                'app_prank_script_id' => '289',
                'app_character_id' => '22',
                'is_default' => '1',
            ],
            [
                'id' => '1571',
                'app_prank_script_id' => '290',
                'app_character_id' => '22',
                'is_default' => '1',
            ],
            [
                'id' => '1572',
                'app_prank_script_id' => '291',
                'app_character_id' => '22',
                'is_default' => '1',
            ],
            [
                'id' => '1573',
                'app_prank_script_id' => '90',
                'app_character_id' => '22',
                'is_default' => '1',
            ],
            [
                'id' => '1574',
                'app_prank_script_id' => '91',
                'app_character_id' => '22',
                'is_default' => '1',
            ],
            [
                'id' => '1575',
                'app_prank_script_id' => '92',
                'app_character_id' => '22',
                'is_default' => '1',
            ],
            [
                'id' => '1576',
                'app_prank_script_id' => '93',
                'app_character_id' => '22',
                'is_default' => '1',
            ],
            [
                'id' => '1577',
                'app_prank_script_id' => '94',
                'app_character_id' => '22',
                'is_default' => '1',
            ],
            [
                'id' => '1578',
                'app_prank_script_id' => '95',
                'app_character_id' => '22',
                'is_default' => '1',
            ],
            [
                'id' => '1579',
                'app_prank_script_id' => '96',
                'app_character_id' => '22',
                'is_default' => '1',
            ],
            [
                'id' => '1580',
                'app_prank_script_id' => '97',
                'app_character_id' => '22',
                'is_default' => '1',
            ],
            [
                'id' => '1581',
                'app_prank_script_id' => '98',
                'app_character_id' => '22',
                'is_default' => '1',
            ],
            [
                'id' => '1582',
                'app_prank_script_id' => '99',
                'app_character_id' => '22',
                'is_default' => '1',
            ],
            [
                'id' => '1583',
                'app_prank_script_id' => '100',
                'app_character_id' => '22',
                'is_default' => '1',
            ],
            [
                'id' => '1584',
                'app_prank_script_id' => '101',
                'app_character_id' => '22',
                'is_default' => '1',
            ],
            [
                'id' => '1585',
                'app_prank_script_id' => '102',
                'app_character_id' => '22',
                'is_default' => '1',
            ],
            [
                'id' => '1586',
                'app_prank_script_id' => '103',
                'app_character_id' => '22',
                'is_default' => '1',
            ],
            [
                'id' => '1587',
                'app_prank_script_id' => '104',
                'app_character_id' => '22',
                'is_default' => '1',
            ],
            [
                'id' => '1588',
                'app_prank_script_id' => '105',
                'app_character_id' => '22',
                'is_default' => '1',
            ],
            [
                'id' => '1589',
                'app_prank_script_id' => '106',
                'app_character_id' => '22',
                'is_default' => '1',
            ],
            [
                'id' => '1590',
                'app_prank_script_id' => '107',
                'app_character_id' => '22',
                'is_default' => '1',
            ],
            [
                'id' => '1591',
                'app_prank_script_id' => '108',
                'app_character_id' => '22',
                'is_default' => '1',
            ],
            [
                'id' => '1592',
                'app_prank_script_id' => '109',
                'app_character_id' => '22',
                'is_default' => '1',
            ],
            [
                'id' => '1593',
                'app_prank_script_id' => '110',
                'app_character_id' => '22',
                'is_default' => '1',
            ],
            [
                'id' => '1594',
                'app_prank_script_id' => '111',
                'app_character_id' => '22',
                'is_default' => '1',
            ],
            [
                'id' => '1598',
                'app_prank_script_id' => '115',
                'app_character_id' => '24',
                'is_default' => '1',
            ],
            [
                'id' => '1715',
                'app_prank_script_id' => '213',
                'app_character_id' => '4',
                'is_default' => '1',
            ],
            [
                'id' => '1716',
                'app_prank_script_id' => '214',
                'app_character_id' => '30',
                'is_default' => '1',
            ],
            [
                'id' => '1717',
                'app_prank_script_id' => '215',
                'app_character_id' => '30',
                'is_default' => '1',
            ],
            [
                'id' => '1718',
                'app_prank_script_id' => '216',
                'app_character_id' => '30',
                'is_default' => '1',
            ],
            [
                'id' => '1724',
                'app_prank_script_id' => '222',
                'app_character_id' => '36',
                'is_default' => '1',
            ],
            [
                'id' => '1725',
                'app_prank_script_id' => '223',
                'app_character_id' => '36',
                'is_default' => '1',
            ],
            [
                'id' => '1726',
                'app_prank_script_id' => '224',
                'app_character_id' => '23',
                'is_default' => '1',
            ],
            [
                'id' => '1727',
                'app_prank_script_id' => '225',
                'app_character_id' => '13',
                'is_default' => '1',
            ],
            [
                'id' => '1728',
                'app_prank_script_id' => '226',
                'app_character_id' => '13',
                'is_default' => '1',
            ],
            [
                'id' => '1729',
                'app_prank_script_id' => '227',
                'app_character_id' => '4',
                'is_default' => '1',
            ],
            [
                'id' => '1730',
                'app_prank_script_id' => '231',
                'app_character_id' => '23',
                'is_default' => '1',
            ],
            [
                'id' => '1731',
                'app_prank_script_id' => '232',
                'app_character_id' => '23',
                'is_default' => '1',
            ],
            [
                'id' => '1732',
                'app_prank_script_id' => '228',
                'app_character_id' => '37',
                'is_default' => '1',
            ],
            [
                'id' => '1733',
                'app_prank_script_id' => '229',
                'app_character_id' => '37',
                'is_default' => '1',
            ],
            [
                'id' => '1734',
                'app_prank_script_id' => '230',
                'app_character_id' => '37',
                'is_default' => '1',
            ],
            [
                'id' => '1735',
                'app_prank_script_id' => '233',
                'app_character_id' => '23',
                'is_default' => '1',
            ],
            [
                'id' => '1736',
                'app_prank_script_id' => '234',
                'app_character_id' => '23',
                'is_default' => '1',
            ],
            [
                'id' => '1737',
                'app_prank_script_id' => '217',
                'app_character_id' => '39',
                'is_default' => '1',
            ],
            [
                'id' => '1738',
                'app_prank_script_id' => '218',
                'app_character_id' => '39',
                'is_default' => '1',
            ],
            [
                'id' => '1739',
                'app_prank_script_id' => '19',
                'app_character_id' => '28',
                'is_default' => '0',
            ],
            [
                'id' => '1740',
                'app_prank_script_id' => '115',
                'app_character_id' => '39',
                'is_default' => '0',
            ],
            [
                'id' => '1741',
                'app_prank_script_id' => '235',
                'app_character_id' => '28',
                'is_default' => '1',
            ],
            [
                'id' => '1742',
                'app_prank_script_id' => '116',
                'app_character_id' => '39',
                'is_default' => '1',
            ],
            [
                'id' => '1743',
                'app_prank_script_id' => '113',
                'app_character_id' => '39',
                'is_default' => '1',
            ],
            [
                'id' => '1744',
                'app_prank_script_id' => '117',
                'app_character_id' => '39',
                'is_default' => '1',
            ],
            [
                'id' => '1745',
                'app_prank_script_id' => '114',
                'app_character_id' => '39',
                'is_default' => '1',
            ],
            [
                'id' => '1746',
                'app_prank_script_id' => '236',
                'app_character_id' => '28',
                'is_default' => '1',
            ],
            [
                'id' => '1747',
                'app_prank_script_id' => '112',
                'app_character_id' => '39',
                'is_default' => '1',
            ],
            [
                'id' => '1748',
                'app_prank_script_id' => '219',
                'app_character_id' => '39',
                'is_default' => '1',
            ],
            [
                'id' => '1749',
                'app_prank_script_id' => '220',
                'app_character_id' => '39',
                'is_default' => '1',
            ],
            [
                'id' => '1750',
                'app_prank_script_id' => '221',
                'app_character_id' => '28',
                'is_default' => '0',
            ],
            [
                'id' => '1751',
                'app_prank_script_id' => '221',
                'app_character_id' => '39',
                'is_default' => '1',
            ],
            [
                'id' => '1752',
                'app_prank_script_id' => '213',
                'app_character_id' => '28',
                'is_default' => '0',
            ],
            [
                'id' => '1753',
                'app_prank_script_id' => '237',
                'app_character_id' => '28',
                'is_default' => '1',
            ],
            [
                'id' => '1754',
                'app_prank_script_id' => '238',
                'app_character_id' => '28',
                'is_default' => '1',
            ],
            [
                'id' => '1755',
                'app_prank_script_id' => '239',
                'app_character_id' => '28',
                'is_default' => '1',
            ],
            [
                'id' => '1756',
                'app_prank_script_id' => '240',
                'app_character_id' => '38',
                'is_default' => '1',
            ],
            [
                'id' => '1757',
                'app_prank_script_id' => '241',
                'app_character_id' => '38',
                'is_default' => '1',
            ],
            [
                'id' => '1758',
                'app_prank_script_id' => '242',
                'app_character_id' => '38',
                'is_default' => '1',
            ],
        ];

        $table = $this->table('app_prank_scripts_app_characters');
        $table->insert($data)->save();
    }
}
